### ISSUE TITLE
chore: set diagnostic setting default value

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-azurerm-app-config#7]
As of today the default value for `diagnostic_setting_enabled_log_categories` set to `["Audit"]`.

In the Microsoft documentation it states that the `Audit` log category cost to export, ref. [Microsoft.AppConfiguration/configurationStores](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/resource-logs-categories#microsoftappconfigurationconfigurationstores).
- Questioning if it still should be enabled by default due to the export cost?

Also, SNYK reports missing log categories `Administrative`, `Alert`, `Policy` and `Security`. Ref. [SNYK-CC-AZURE-552](https://snyk.io/security-rules/SNYK-CC-AZURE-552), although they are not listed in the documentation or by CLI command. 
- Should this be looked more into?
- There is alreadey an open issue regarding this: #6 

Confirmed the log categories by listing them with `az monitor diagnostic-settings-categories list --resource <resource_id>`:
```json
    {
      "categoryType": "Logs",
      "id": "/subscriptions/<subscription_id>/resourcegroups/rg-aa8d31e229348137/providers/microsoft.appconfiguration/configurationstores/appcs-aa8d31e229348137/providers/microsoft.insights/diagnosticSettingsCategories/HttpRequest",
      "name": "HttpRequest",
      "resourceGroup": "rg-aa8d31e229348137",
      "type": "microsoft.insights/diagnosticSettingsCategories"
    }
    {
      "categoryType": "Logs",
      "id": "/subscriptions/<subscription_id>/resourcegroups/rg-aa8d31e229348137/providers/microsoft.appconfiguration/configurationstores/appcs-aa8d31e229348137/providers/microsoft.insights/diagnosticSettingsCategories/Audit",
      "name": "Audit",
      "resourceGroup": "rg-aa8d31e229348137",
      "type": "microsoft.insights/diagnosticSettingsCategories"
    },
```

**Comment by helenakallekleiv** [comment]
@hknutsen Any thoughts on this?

**Comment by hknutsen** [comment]
Good observations 🙂 

We always want to enable any kind of audit logging by default (unless the cost is extraordinarily high) to track all user interaction with the resource (which is why the default name for the diagnostic setting in all of our modules is `audit-logs` btw. 🙂).

Regarding Snyk recommending log categories `Administrative`, `Alert`, `Policy` and `Security`: those are the recommended categories to enable at the **subscription** scope (see [this example](https://github.com/equinor/terraform-azurerm-log-analytics/blob/v1.5.0/examples/export-activity-logs/main.tf#L25-L45)). Snyk can't tell which scope you're trying to create the diagnostic setting for, so it just recommends those for whatever reason 🤷 We've been getting this recommendation from Snyk for all our modules, but I usually just ignore it.
